"""Create category and question tables

Revision ID: 42133f2b8a35
Revises:
Create Date: 2020-07-28 15:34:10.434741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "42133f2b8a35"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "category",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"))
    op.create_table(
        "question",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("question", sa.String(), nullable=True),
        sa.Column("choices", sa.String(), nullable=True),
        sa.Column("answer", sa.String(), nullable=True),
        sa.Column("category_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["category_id"], ["category.id"],),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("question")
    op.drop_table("category")
    # ### end Alembic commands ###
